phy=int(input("enter the marks of physics:"))
che=int(input("enter the marks of chemistry"))
maths=int(input("enter the marks of maths"))
python=int(input("enter the marks of python"))
eng=int(input("enter the marks of english"))
total=(phy+che+eng+maths+python)
avg=total/5
print("********************************")
print("***********dy patil*************")
print("Name:Guido van rossum")
print("Roll no:114")
print("Address:shattevadi,uptevadi,under water tank")
print("Physics:",phy)
print("chemistry:",che)
print("maths:",maths)
print("Python",python)
print("English:",eng)
print("total:",total)
print("Average:",avg)